server:
  port: 10000

spring:
  application:
    name: rical-backend-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://82.156.216.48:3306/user_center
    hikari:
      username: root
      password: wtMysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - dversion
      - swagger
      - job